spring:
  application:
    name: api-config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo/ # Asumiendo ejecución desde la raíz del proyecto donde está config-repo
  profiles:
    active: native # Asegurarse de que el perfil native esté activo

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops # Exponer más endpoints para depuración
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

info:
  app:
    name: api-config-server
    description: API Config Server (Native Backend)
    version: 1.0.0

eureka:
  instance:
    instance-id: MMSTechnology-Personal-Admin:${spring.application.name}:${server.port}
    statusPageUrlPath: http://localhost:8888/actuator/info # Usar localhost para URLs de instancia si Eureka está en localhost
    healthCheckUrlPath: http://localhost:8888/actuator/health # Usar localhost
    # Preferir la IP para el registro en Eureka si hay problemas con hostname
    # prefer-ip-address: true
    # hostname: localhost # Fijar el hostname si es necesario
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
